LMarinBorges/henry-pf

- packages/frontend/src/pages/home.tsx
fue creada la landing-page, faltan detalles, colores, etc.
> feat(pages/home): create landing-page

- packages/backend/src/modules/categories/categories.controller.ts
- packages/backend/src/modules/categories/categories.router.ts
Added delete and search by id function
> feat: added category by id  and delete category

- packages/frontend/src/App.tsx
- packages/frontend/src/pages/products/product.tsx
Creacion de la card del producto ||  fix de la ruta products/productId
> feat(products/product): create product card

- packages/frontend/src/pages/contact.tsx
formulario y informacion creada
> feat(front/contact): formulario e info creada

- packages/frontend/src/components/PublicLayout/Footer.tsx
> feat(publiclayout/footer): create-footer

- packages/frontend/src/pages/products/product.tsx
Creacion de pagina de producto_ID de muestra, sin funcionalidad implementada, próxima a refactorizar  para ser responsive y con actualizaciones de comentarios y puntuación en tiempo real
> feat(products/product): create_productid_page

- packages/frontend/src/feature/SearchBar.tsx
> feat(front/searchBar): searchBar creado

- packages/frontend/src/components/PublicLayout/Footer.tsx
> fix(public-layaout/footer): add icons

- packages/backend/src/app.ts
- packages/backend/src/modules/users/index.ts
- packages/backend/src/modules/users/users.controller.ts
- packages/backend/src/modules/users/users.router.ts
> build(backend): create user module

- packages/backend/prisma/schema.prisma
Creación del modelo Review y la relación entre las tablas User y Product.
> feat(backend-create_model_review): create model review

- packages/backend/src/modules/users/users.controller.ts
- packages/backend/src/modules/users/users.router.ts
Creacion de update del user(falta implementar password y catch)
> feat: add update user route

- packages/frontend/src/pages/products/index.tsx
- packages/frontend/src/redux/actions/index.ts
Creacion del Select Brands, coneccion de select Brand  y corrección de errores del Select Categories
> feat(products & redux): conect_filters

- packages/backend/src/modules/products/products.controller.ts
añadí una nueva columna para que pueda filtrar por la columna isTrashed , de modo que puedan añadir una accion para que lo llame de esa forma o modificar las acciones actuales
> fix: getAllSchema and getAllProducts

- packages/frontend/src/components/PublicLayout/Navbar.tsx
- packages/frontend/src/feature/ToggleColorMode.tsx
- packages/frontend/src/main.tsx
- packages/frontend/src/pages/home.tsx
- packages/frontend/src/theme/theme.tsx
Se creo boton dark-mode
se creo la carpeta "theme" para configuracion globales de styles
> feat(feature/toggle-color-mode): add button dark-mode

- packages/frontend/src/pages/admin/editTable/EditTable.tsx
- packages/frontend/src/pages/admin/products.tsx
- packages/frontend/src/redux/actions/index.ts
en admin/products ya se puede modificar la tabla
> feat(front/editTable): ya se puede modificar la tabla en admin

- packages/frontend/src/features/components/loginButton.tsx
Añadí un icono que reemplaza a los dos botones de registro y login en caso de que la pantalla sea muy pequeña
> feat(public): add icon login for responsive design

- packages/backend/prisma/schema.prisma
Creación del modelo de Orders  (ordenes de compras) y sus relaciones con Products y Users.
> feat(backend-order_model): create order model

- packages/frontend/src/App.tsx
- packages/frontend/src/features/components/CreateProductForm.tsx
se agregaron validaciones y algunos styles al form
> fix(components/create-product-form): se agregaron validaciones

- packages/frontend/src/components/PublicLayout/Footer.tsx
- packages/frontend/src/components/PublicLayout/Navbar.tsx
- packages/frontend/src/pages/home.tsx
se arregló navbar para que al scrollear nada se le superponga
se arregló botón de carrito de compras para el modo-oscuro
> fix(publiclayout/footer): fix navbar

- packages/frontend/src/feature/searchBar/SearchBar.tsx
- packages/frontend/src/pages/products/index.tsx
> fix(pages/products/index): edit styles

- packages/frontend/src/features/components/CreateProductForm.tsx
- packages/frontend/src/pages/admin/Table.tsx
- packages/frontend/src/pages/admin/createBrands/CreateBrands.tsx
- packages/frontend/src/redux/actions/index.ts
- packages/frontend/src/redux/reducer/index.ts
crea correctamente y tiene validación
> feat(front/createBrands): form para crear marca

- packages/frontend/src/pages/contact.tsx
- packages/frontend/src/pages/products/index.tsx
> fix(pages/contact): fix styles dark-mode

- packages/frontend/src/features/components/CreateProductForm.tsx
- packages/frontend/src/pages/admin/createCategories/CreateCategories.tsx
- packages/frontend/src/pages/admin/editTable/EditTable.tsx
- packages/frontend/src/redux/actions/index.ts
- packages/frontend/src/redux/reducer/index.ts
funciona correctamente y tiene validacion.
> feat(front/create_Categories): boton de crear categorias listo

- packages/frontend/src/App.tsx
- packages/frontend/src/components/AdminLayout/Navbar.tsx
- packages/frontend/src/features/components/loginButton.tsx
- packages/frontend/src/pages/products/BuyForm.tsx
> feat(products/buy-form): create form buy

- packages/frontend/src/App.tsx
- packages/frontend/src/pages/products/urlsBack/Failed.tsx
- packages/frontend/src/pages/products/urlsBack/Pending.tsx
- packages/frontend/src/pages/products/urlsBack/Successful.tsx
creacion de urls para back listo
> feat(front/urlsBack): add urls to the back

- packages/backend/src/config.ts
- packages/backend/src/modules/users/facebook.routes.ts
- packages/backend/src/modules/users/google.routes.ts
- packages/frontend/src/redux/actions/index.ts
corregido el bug en el cual la ventana de autenticación de terceros no se cerraba ni enviaba los datos del usuario al lado del cliente.
> fix(auth): fix problem with third party auth

- packages/backend/src/modules/mailer/mailer.controller.ts
- packages/backend/src/modules/mailer/mailer.router.ts
- packages/frontend/src/features/components/LoginRegisterForm.tsx
- packages/frontend/src/redux/actions/index.ts
Agreagado de email con front, fix del boton de registrar
> feat: send email when user register

- packages/frontend/src/pages/admin/Table.tsx
- packages/frontend/src/pages/admin/users/DinamicTable.tsx
- packages/frontend/src/pages/admin/users/modalEdit.tsx
ahora se puede hacer scroll correctamente y que aparezcan todas las columnas de todas las tablas
> style(front/tables): responsive

- packages/frontend/src/pages/admin/editTable/EditTable.tsx
quite el id en el formulario de Edit en la parte del Admin
> refactor(front/editTable): remover el id del form Edit

- packages/backend/src/modules/orders/orders.controller.ts
- packages/frontend/src/pages/products/BuyForm.tsx
- packages/frontend/src/pages/products/card.tsx
- packages/frontend/src/pages/products/shoppingcart.tsx
- packages/frontend/src/redux/actions/index.ts
arreglado el error que linkeaba toda la card, ahora solo se accede al detalle de producto desde el click en la imagen o nombre del producto y no en cualquier parte de la card
> Fix cards menu

- packages/backend/src/modules/orders/orders.controller.ts
- packages/frontend/src/pages/products/BuyForm.tsx
- packages/frontend/src/pages/products/shoppingcart.tsx
- packages/frontend/src/redux/actions/index.ts
Se llega a completar la transaccion pero no redirecciona a ninguna página, proximo fix para mañana
> fix(mercadopago): transaction_approved

- packages/backend/src/modules/users/users.controller.ts
- packages/frontend/src/features/components/LoginRegisterForm.tsx
- packages/frontend/src/redux/actions/index.ts
Toast en caso de errores y exito
> fix: toast in local register

- packages/frontend/src/features/components/LoginRegisterForm.tsx
- packages/frontend/src/redux/actions/index.ts
agregado de nodemailer con google y toast al iniciar sesion
> fix: add nodemailer with google

- packages/frontend/src/pages/products/BuyForm.tsx
- packages/frontend/src/pages/products/shoppingcart.tsx
agregue titulo y modo oscuro al formulario de compra (buyform)
> Fix buyform darkmode

- packages/frontend/src/components/PublicLayout/Footer.tsx
- packages/frontend/src/components/PublicLayout/Navbar.tsx
- packages/frontend/src/components/PublicLayout/Navbar2.tsx
- packages/frontend/src/components/PublicLayout/index.tsx
- packages/frontend/src/pages/home.tsx
> fix(public-layout/navbar): fix navbar bug

- packages/backend/src/modules/mailer/mailer.controller.ts
- packages/backend/src/modules/mailer/mailer.router.ts
- packages/frontend/src/features/components/LoginRegisterForm.tsx
- packages/frontend/src/redux/actions/index.ts
Agregado y manejo de errores con toas y envio de mail al hacer login
> Feat: add session mail and toast

- packages/frontend/src/features/components/CreateProductForm.tsx
- packages/frontend/src/pages/admin/orders/searchBar.tsx
- packages/frontend/src/pages/contact.tsx
- packages/frontend/src/pages/products/index.tsx
- packages/frontend/src/pages/products/shoppingCard.tsx
- packages/frontend/src/pages/products/shoppingcart.tsx
> style: shopping cart

- packages/frontend/src/pages/contact.tsx
- packages/frontend/src/redux/actions/index.ts
con validacion y alerta de confirmacion
> feat(front/contact): funcionalidad al form contact

- packages/frontend/src/pages/home.tsx
- packages/frontend/src/pages/products/index.tsx
- packages/frontend/src/pages/suscribe/Suscribe.tsx
- packages/frontend/src/redux/actions/index.ts
todo listo, con validacion y alerta de confirmacion
> feat(front/suscribe): funcionalidad al boton get started

- packages/frontend/src/pages/products/BuyForm.tsx
- packages/frontend/src/pages/products/product.tsx
- packages/frontend/src/pages/products/shoppingCard.tsx
- packages/frontend/src/pages/products/shoppingcart.tsx
Arreglado el problema del formulario de compras
> fix(mercadopago): fixed_form_error

- packages/frontend/src/features/components/CreateProductForm.tsx
Añadido la limpieza del src de Imagen luego del submit , en el form para crear productos
> feat(frontend/product): add setpreview null

- packages/backend/src/modules/mailer/mailer.controller.ts
- packages/backend/src/modules/mailer/mailer.router.ts
- packages/frontend/src/features/components/LoginRegisterForm.tsx
> fix: toast top

- packages/frontend/src/pages/admin/users/tableUsers.tsx
agregado un loader que se muestra en caso aun no hayan datos o no haya usuarios para mostrar , también arreglé la condición para el renderizado de la tabla
> feat(frontend/users): add loader in users table

- packages/backend/src/modules/mailer/mailer.controller.ts
- packages/backend/src/modules/mailer/mailer.router.ts
- packages/frontend/src/pages/admin/Table.tsx
- packages/frontend/src/pages/admin/products.tsx
- packages/frontend/src/pages/contact.tsx
- packages/frontend/src/pages/products/BuyForm.tsx
- packages/frontend/src/pages/products/card.tsx
- packages/frontend/src/pages/products/product.tsx
- packages/frontend/src/redux/actions/index.ts
agregado de mail en contactos y suscripcion junto con arreglos menores
> Feat(nodemailer & correcion): agregado de mail en contactos y suscripcion junto con arreglos menores

- packages/frontend/src/pages/products/shoppingCard.tsx
- packages/frontend/src/pages/products/shoppingcart.tsx
Corrección bug eliminar del carrito de compras
> fix(products/shoppingcart): fixed_delete_shoppingcart
